"""
Domain models for AutoDBAudit.

This module contains the core business entities that represent:
- Audit runs and their results
- Requirements and compliance status
- Actions taken and exceptions documented
- Server and instance information

These models are pure data structures with no I/O dependencies.
They can be serialized to/from SQLite via the infrastructure layer.

Note: Using slots=True for memory efficiency and slightly faster attribute access.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any


# ============================================================================
# Enumerations
# ============================================================================

class AuditStatus(Enum):
    """Status of an audit run."""
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class RequirementStatus(Enum):
    """Status of a requirement check result."""
    PASS = "pass"
    FAIL = "fail"
    EXCEPTION = "exception"
    NOT_APPLICABLE = "not_applicable"
    PENDING = "pending"


class Severity(Enum):
    """Severity level for requirements and findings."""
    CRITICAL = "critical"
    WARNING = "warning"
    INFO = "info"


class ActionType(Enum):
    """Type of remediation action."""
    APPLIED = "applied"
    SKIPPED = "skipped"
    FAILED = "failed"


# ============================================================================
# Core Domain Models (Phase 1 - Simplified)
# ============================================================================

@dataclass(slots=True)
class AuditRun:
    """
    Represents a single audit execution.
    
    Attributes:
        id: Unique identifier (auto-generated by SQLite)
        started_at: Timestamp when audit started (UTC)
        ended_at: Timestamp when audit completed (None if in progress)
        organization: Name of the organization being audited
        status: Current status ("pending", "running", "completed", "failed")
        config_hash: SHA256 hash of config used (for reproducibility)
    """
    id: int | None = None
    started_at: datetime | None = None
    ended_at: datetime | None = None
    organization: str | None = None
    status: str = "pending"
    config_hash: str | None = None


@dataclass(slots=True)
class Server:
    """
    Represents a SQL Server host machine.
    
    Attributes:
        id: Unique identifier
        hostname: Server hostname (used for connections)
        ip_address: IP address (optional, for documentation)
    """
    id: int | None = None
    hostname: str = ""
    ip_address: str | None = None


@dataclass(slots=True)
class Instance:
    """
    Represents a SQL Server instance on a server.
    
    Attributes:
        id: Unique identifier
        server_id: Foreign key to Server
        instance_name: Instance name (empty string for default instance)
        port: TCP port (default 1433, used to distinguish instances on same host)
        version: Full version string (e.g., "15.0.4298.1")
        version_major: Major version number (10=2008, 15=2019, 16=2022)
        edition: Edition name (e.g., "Standard Edition (64-bit)")
        product_level: Service pack / CU level (e.g., "RTM", "SP1", "CU22")
    """
    id: int | None = None
    server_id: int | None = None
    instance_name: str = ""
    port: int = 1433
    version: str = ""
    version_major: int = 0
    edition: str | None = None
    product_level: str | None = None


# ============================================================================
# Future Models (Stubs for Phase 2+)
# ============================================================================

@dataclass(slots=True)
class Requirement:
    """
    Represents a security/compliance requirement from db-requirements.md.
    
    TODO: Expand in Phase 2 when implementing requirement checks.
    """
    id: int = 0
    code: str = ""
    title: str = ""
    description: str = ""
    severity: Severity = Severity.WARNING
    category: str | None = None


@dataclass(slots=True)
class RequirementResult:
    """
    Result of checking a requirement against a specific instance.
    
    TODO: Expand in Phase 2 when implementing requirement checks.
    """
    id: int | None = None
    audit_run_id: int | None = None
    instance_id: int | None = None
    requirement_id: int | None = None
    status: RequirementStatus = RequirementStatus.PENDING
    finding: str | None = None
    evidence: str | None = None  # JSON string
    checked_at: datetime | None = None


@dataclass(slots=True)
class Action:
    """
    Represents a remediation action taken.
    
    TODO: Expand in Phase 4 when implementing remediation.
    """
    id: int | None = None
    audit_run_id: int | None = None
    instance_id: int | None = None
    requirement_id: int | None = None
    action_type: ActionType = ActionType.SKIPPED
    script_file: str | None = None
    executed_at: datetime | None = None
    result_message: str | None = None


# ============================================================================
# Type Aliases
# ============================================================================

# For SQLite row data before conversion to model
RawRow = dict[str, Any]
