"""
Remediation handler for Infrastructure properties, Linked Servers, Backups, and Info.
"""

from __future__ import annotations

from autodbaudit.application.remediation.handlers.base import (
    RemediationHandler,
    RemediationAction,
)


class InfrastructureHandler(RemediationHandler):
    """
    Handles Linked Servers, Backups, Version Info, Encryption Info.
    """

    def handle(self, finding: dict) -> list[RemediationAction]:
        """Generate actions."""
        ft = finding["finding_type"]
        entity = finding["entity_name"]
        desc = finding.get("finding_description", "") or ""

        actions = []

        if ft == "linked_server":
            # Always REVIEW
            script = self._script_review_linked_server(entity, desc)
            actions.append(RemediationAction(script, "-- Manual action", "REVIEW"))

        elif ft == "backup":
            # Always INFO
            script = self._script_info_backup(entity)
            actions.append(RemediationAction(script, "", "INFO"))

        elif ft == "version":
            # Always INFO
            script = self._script_info_version_upgrade()
            actions.append(RemediationAction(script, "", "INFO"))

        elif ft == "encryption":
            # Always INFO (detected via info_section logic in old service, but here triggered by finding)
            # Wait, logic in old service: if has_encryption_finding -> info.
            # Actually, old logic: `info_section.append(self._script_info_encryption())` was ALWAYS added at end.
            # We should probably handle that in the Service or here if finding exists.
            # Ideally, we add a single INFO script for all encryption findings.
            pass

        return actions

    def get_global_info_scripts(self) -> list[RemediationAction]:
        """Return scripts that should always be included (like encryption info)."""
        # This mirrors the unconditional `info_section.append(self._script_info_encryption())`
        return [RemediationAction(self._script_info_encryption(), "", "INFO")]

    def _script_review_linked_server(self, server_name: str, desc: str) -> str:
        header = self._item_header("👀 REVIEW", f"Linked Server: {server_name}")
        return f"""{header}
/*
ISSUE: {desc}
Linked Server: {server_name}

RECOMMENDATION: Review RPC configuration and necessity.
*/
-- EXEC master.dbo.sp_dropserver @server=N'{server_name}', @droplogins='droplogins';
"""

    def _script_info_backup(self, entity: str) -> str:
        header = self._item_header("ℹ️ INFO", f"Backup Issue: {entity}")
        return f"""{header}
/*
ISSUE: Missing backups detected for {entity.replace('|', ' -> ')}.
action:
1. Check SQL Server Agent jobs.
2. Verify Maintenance Plans.
3. Ensure Transaction Log backups are running for FULL recovery model.
*/
"""

    def _script_info_version_upgrade(self) -> str:
        header = self._item_header("ℹ️ UPDATE", "SQL Server Version Update Available")
        return f"""{header}
/*
ISSUE: SQL Server version is older than the expected baseline.
RECOMMENDATION: Plan an upgrade to the latest Service Pack and Cumulative Update.

Resources:
- https://sqlserverbuilds.blogspot.com/
- https://learn.microsoft.com/en-us/sql/database-engine/install-windows/latest-updates-for-microsoft-sql-server
*/
"""

    def _script_info_encryption(self) -> str:
        header = self._item_header("ℹ️ INFO", "Encryption Status")
        return f"""{header}
/*
Encryption Hierarchy:
- Verify Service Master Key (SMK) is backed up.
- Verify Database Master Keys (DMK) are backed up.
- Rotate Certificates periodically.

To view keys:
SELECT db_name(database_id), * FROM sys.dm_database_encryption_keys;
*/
"""

    def generate_os_script(self) -> str:
        """Generate a comprehensive PowerShell script for OS-level audit and remediation."""

        # CRITICAL: Do not generate PowerShell for non-Windows hosts
        if self.ctx.host_platform and self.ctx.host_platform.lower() != "windows":
            return f"""# UNIX/LINUX DETECTED
# PowerShell remediation is skipped for {self.ctx.host_platform}.
# Please use manual remediation for OS-level settings.
"""

        return f"""<#
.SYNOPSIS
    OS-Level Audit and Remediation Script for {self.ctx.server_name}
.DESCRIPTION
    Checks and optionally remediates Windows-level settings.
    COMPATIBILITY: Windows Server 2008 R2+ (PowerShell v2.0+)
    - Services (SQL Browser, Agent, CEIP)
    - Client Protocols (Registry)
    - Firewall Ports ({self.ctx.port}) via NETSH
    - Windows Power Plan via WMI
.NOTES
    Generated by AutoDBAudit for {self.ctx.server_name}
    Aggressiveness: {self.ctx.aggressiveness}
#>

[CmdletBinding()]
Param(
    [switch]$ApplyFix = $false
)

$ServerName = "{self.ctx.server_name}"
$InstanceName = "{self.ctx.instance_name or 'MSSQLSERVER'}"
$Port = {self.ctx.port}
$Aggressiveness = {self.ctx.aggressiveness}
$ServiceName = "MSSQL`$$InstanceName"
if ($InstanceName -eq "MSSQLSERVER") {{ $ServiceName = "MSSQLSERVER" }}

Write-Host "=== Starting OS Audit for $ServerName ===" -ForegroundColor Cyan
Write-Host "Service Name: $ServiceName"
Write-Host "Mode: $(if ($ApplyFix -or $Aggressiveness -ge 2) {{ 'REMEDIATION' }} else {{ 'AUDIT ONLY' }})" -ForegroundColor Gray

# Helper: Check and Fix Registry
function Set-RegistryValue {{
    param($Path, $Name, $DesiredValue, $Type="DWord")
    if (Test-Path $Path) {{
        $current = Get-ItemProperty -Path $Path -Name $Name -ErrorAction SilentlyContinue
        if ($null -eq $current -or $current.$Name -ne $DesiredValue) {{
            Write-Host "  [WARN] Registry $Name at $Path is not $DesiredValue" -ForegroundColor Yellow
            if ($ApplyFix -or $Aggressiveness -ge 2) {{
                Write-Host "  [FIX] Setting $Name to $DesiredValue..."
                New-ItemProperty -Path $Path -Name $Name -Value $DesiredValue -PropertyType $Type -Force | Out-Null
                Write-Host "  [OK] Updated." -ForegroundColor Green
                return $true # Changed
            }}
        }} else {{
            Write-Host "  [PASS] Registry $Name is correct ($DesiredValue)." -ForegroundColor Green
        }}
    }} else {{
        Write-Host "  [ERR] Registry path not found: $Path" -ForegroundColor Red
    }}
    return $false
}}

$RestartRequired = $false

# 1. Services Audit
Write-Host "`n[1] Checking Services..."

# Helper: Disable and Stop Service (robust with retry/wait)
function Disable-SqlService {{
    param([string]$ServiceName, [string]$DisplayName)
    $svc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($svc) {{
        if ($svc.StartType -ne 'Disabled' -or $svc.Status -eq 'Running') {{
            Write-Host "  [WARN] $DisplayName ($ServiceName) is $($svc.Status)/$($svc.StartType)" -ForegroundColor Yellow
            if ($ApplyFix -or $Aggressiveness -ge 2) {{
                Write-Host "  [FIX] Disabling $DisplayName..."
                try {{
                    Set-Service -Name $ServiceName -StartupType Disabled -ErrorAction Stop
                    if ($svc.Status -eq 'Running') {{
                        Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
                        # Wait up to 15 seconds for stop
                        $wait = 15
                        while ((Get-Service -Name $ServiceName -ErrorAction SilentlyContinue).Status -eq 'Running' -and $wait -gt 0) {{
                            Start-Sleep -Seconds 1
                            $wait--
                        }}
                    }}
                    Write-Host "  [OK] $DisplayName disabled." -ForegroundColor Green
                }} catch {{
                    Write-Host "  [ERR] Failed: $_" -ForegroundColor Red
                }}
            }}
        }} else {{
            Write-Host "  [PASS] $DisplayName is Disabled." -ForegroundColor Green
        }}
    }}
}}

# 1.1 SQL Browser
Disable-SqlService -ServiceName "SQLBrowser" -DisplayName "SQL Browser"

# 1.2 SQL Telemetry (CEIP) - different name for default vs named instance
if ($InstanceName -eq "MSSQLSERVER") {{
    Disable-SqlService -ServiceName "SQLTELEMETRY" -DisplayName "SQL Telemetry"
}} else {{
    Disable-SqlService -ServiceName "SQLTELEMETRY`$$InstanceName" -DisplayName "SQL Telemetry"
}}

# 1.3 VSSWriter (SQLWriter) - often not needed
Disable-SqlService -ServiceName "SQLWriter" -DisplayName "SQL VSS Writer"

# 2. Client Protocols
Write-Host "`n[2] Checking Client Protocols..."
$RegBase = "HKLM:\\SOFTWARE\\Microsoft\\Microsoft SQL Server\\"
$InstanceId = (Get-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Microsoft SQL Server\\Instance Names\\SQL" -Name $InstanceName -ErrorAction SilentlyContinue).$InstanceName
if ($InstanceId) {{
    $ProtoPath = "$RegBase$InstanceId\\MSSQLServer\\SuperSocketNetLib"
    
    # 2.1 Disable Named Pipes (Np)
    if (Set-RegistryValue -Path "$ProtoPath\\Np" -Name "Enabled" -DesiredValue 0) {{ $RestartRequired = $true }}
    
    # 2.2 Disable VIA (Sm enabled, Tcp enabled)
    if (Set-RegistryValue -Path "$ProtoPath\\Tcp" -Name "Enabled" -DesiredValue 1) {{ $RestartRequired = $true }}
    if (Set-RegistryValue -Path "$ProtoPath\\Sm" -Name "Enabled" -DesiredValue 1) {{ $RestartRequired = $true }}
}} else {{
    Write-Host "  [SKIP] Could not resolve Instance Root via Registry." -ForegroundColor Red
}}

# 3. Network & Firewall (Legacy Compatible)
Write-Host "`n[3] Network Configuration..."

# IP Address via WMI for 2008 comp
$IPs = Get-WmiObject Win32_NetworkAdapterConfiguration | Where-Object {{ $_.IPEnabled }} | Select-Object -ExpandProperty IPAddress
Write-Host "  [INFO] Detected IPs: $($IPs -join ', ')"

# Firewall via NETSH (Universal)
$fwRuleName = "SQL Server Port $Port"
$netshCheck = netsh advfirewall firewall show rule name="$fwRuleName" 2>&1
if ($netshCheck -match "No rules match") {{
    Write-Host "  [WARN] No firewall rule found for '$fwRuleName'" -ForegroundColor Yellow
    if ($ApplyFix -or $Aggressiveness -ge 3) {{
         Write-Host "  [FIX] Creating Firewall Rule via NETSH..."
         # netsh advfirewall firewall add rule name="SQL Server Port 1433" dir=in action=allow protocol=TCP localport=1433
         netsh advfirewall firewall add rule name="$fwRuleName" dir=in action=allow protocol=TCP localport=$Port | Out-Null
         Write-Host "  [OK] Rule Created." -ForegroundColor Green
    }}
}} else {{
    Write-Host "  [PASS] Firewall rule '$fwRuleName' exists." -ForegroundColor Green
}}

# 4. Power Plan (WMI for 2008 comp)
Write-Host "`n[4] Power Plan..."
$plan = Get-WmiObject -Class Win32_PowerPlan -Namespace root\\cimv2\\power | Where-Object {{ $_.IsActive }}
if ($plan.ElementName -notlike "*High Performance*") {{
    Write-Host "  [WARN] Power Plan is '$($plan.ElementName)' (Expected: High Performance)" -ForegroundColor Yellow
    if ($ApplyFix -or $Aggressiveness -ge 2) {{
         Write-Host "  [FIX] Setting High Performance..."
         $highPerf = Get-WmiObject -Class Win32_PowerPlan -Namespace root\\cimv2\\power | Where-Object {{ $_.ElementName -like "*High Performance*" }}
         if ($highPerf) {{
             $highPerf.Activate()
             Write-Host "  [OK] set to High Performance." -ForegroundColor Green
         }}
    }}
}}

# 5. Restart Logic
if ($RestartRequired) {{
    Write-Host "`n[!] Configuration changes require Service Restart." -ForegroundColor Magenta
    if ($ApplyFix -or $Aggressiveness -ge 3) {{
        Write-Host "  [FIX] Restarting Service $ServiceName..."
        Restart-Service -Name $ServiceName -Force
        if (Get-Service "SQLAgent`$$InstanceName" -ErrorAction SilentlyContinue) {{
             Restart-Service "SQLAgent`$$InstanceName" -Force
        }}
        Write-Host "  [OK] Services Restarted." -ForegroundColor Green
    }} else {{
        Write-Host "  [INFO] Please restart SQL Server manually to apply changes."
    }}
}}

Write-Host "`n=== OS Audit Complete ===" -ForegroundColor Cyan
"""
